name: Build and deploy
on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'bugfix/*'
      - develop
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Build
        run: |
          yarn
          yarn format:all
          yarn lint
          yarn build:firebase

      - name: Deploy
        if: github.ref == 'refs/heads/develop'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
